export const maxTimeRange = [
  2002,
  2023
];

export const productCategories = [
  "Arms and ammunition",
  "Art, collectibles, antiques",
  "Base metals",
  "Chemical products",
  "Edible fats",
  "Food, beverages, spirits, tobacco",
  "Footwear, headgear, accessories",
  "Fur, leather products",
  "Furniture, lighting, toys, misc.",
  "Jewelery, precious metals, coins",
  "Live animals, animal products",
  "Machinery and electronics",
  "Mineral products",
  "Optical, precision instruments",
  "Paper products",
  "Plastic, rubber products",
  "Stone, ceramic, glassware",
  "Textiles",
  "Vegetable products",
  "Vehicles, aircraft, vessels",
  "Wood products"
];

export const groupMappings = {
  "African countries": ["Algeria", "Angola", "Benin", "Botswana", "Burkina Faso", "Burundi", "Cabo Verde", "Cameroon", "Central African Rep.", "Chad", "Comoros", "Congo", "Côte d'Ivoire", "Dem. Rep. of the Congo", "Djibouti", "Egypt", "Equatorial Guinea", "Eritrea", "Eswatini", "Ethiopia", "Gabon", "Gambia", "Ghana", "Guinea", "Guinea-Bissau", "Kenya", "Lesotho", "Liberia", "Libya", "Madagascar", "Malawi", "Mali", "Mauritania", "Mauritius", "Morocco", "Mozambique", "Namibia", "Niger", "Nigeria", "Rwanda", "Sao Tome and Principe", "Senegal", "Seychelles", "Sierra Leone", "Somalia", "South Africa", "South Sudan", "Sudan", "Togo", "Tunisia", "Uganda", "United Rep. of Tanzania", "Zambia", "Zimbabwe"],
  "Algeria": ["Algeria"],
  "Angola": ["Angola"],
  "Argentina": ["Argentina"],
  "Australia": ["Australia"],
  "Austria": ["Austria"],
  "BRICS countries": ["Brazil", "China", "Egypt", "Ethiopia", "India", "Indonesia", "Iran", "Russian Federation", "United Arab Emirates"],
  "Bangladesh": ["Bangladesh"],
  "Belgium": ["Belgium"],
  "Benin": ["Benin"],
  "Botswana": ["Botswana"],
  "Brazil": ["Brazil"],
  "Bulgaria": ["Bulgaria"],
  "Burkina Faso": ["Burkina Faso"],
  "Burundi": ["Burundi"],
  "Cabo Verde": ["Cabo Verde"],
  "Cameroon": ["Cameroon"],
  "Canada": ["Canada"],
  "Central African Rep.": ["Central African Rep."],
  "Chad": ["Chad"],
  "Chile": ["Chile"],
  "China": ["China"],
  "Colombia": ["Colombia"],
  "Comoros": ["Comoros"],
  "Congo": ["Congo"],
  "Croatia": ["Croatia"],
  "Cyprus": ["Cyprus"],
  "Czechia": ["Czechia"],
  "Côte d'Ivoire": ["Côte d'Ivoire"],
  "Dem. Rep. of the Congo": ["Dem. Rep. of the Congo"],
  "Denmark": ["Denmark"],
  "Djibouti": ["Djibouti"],
  "EU27 countries": ["Austria", "Belgium", "Bulgaria", "Croatia", "Cyprus", "Czechia", "Denmark", "Estonia", "Finland", "France", "Germany", "Greece", "Hungary", "Ireland", "Italy", "Latvia", "Lithuania", "Luxembourg", "Malta", "Netherlands", "Poland", "Portugal", "Romania", "Slovakia", "Slovenia", "Spain", "Sweden"],
  "Easbtern African countries": ["Uganda"],
  "Eastern African countries": ["Burundi", "Comoros", "Djibouti", "Eritrea", "Ethiopia", "Kenya", "Madagascar", "Malawi", "Mauritius", "Mozambique", "Rwanda", "Seychelles", "Somalia", "South Sudan", "United Rep. of Tanzania", "Zambia", "Zimbabwe"],
  "Ecuador": ["Ecuador"],
  "Egypt": ["Egypt"],
  "Equatorial Guinea": ["Equatorial Guinea"],
  "Eritrea": ["Eritrea"],
  "Estonia": ["Estonia"],
  "Eswatini": ["Eswatini"],
  "Ethiopia": ["Ethiopia"],
  "Finland": ["Finland"],
  "France": ["France"],
  "G20 countries": ["Argentina", "Australia", "Brazil", "Canada", "China", "France", "Germany", "India", "Indonesia", "Italy", "Japan", "Mexico", "Rep. of Korea", "Russian Federation", "Saudi Arabia", "South Africa", "Türkiye", "USA", "United Kingdom"],
  "G7 countries": ["Canada", "France", "Germany", "Italy", "Japan", "USA", "United Kingdom"],
  "Gabon": ["Gabon"],
  "Gambia": ["Gambia"],
  "Germany": ["Germany"],
  "Ghana": ["Ghana"],
  "Greece": ["Greece"],
  "Guinea": ["Guinea"],
  "Guinea-Bissau": ["Guinea-Bissau"],
  "Guyana": ["Guyana"],
  "Horn of Africa countries": ["Djibouti", "Eritrea", "Ethiopia", "Somalia"],
  "Hungary": ["Hungary"],
  "India": ["India"],
  "Indonesia": ["Indonesia"],
  "Iran": ["Iran"],
  "Ireland": ["Ireland"],
  "Italy": ["Italy"],
  "Japan": ["Japan"],
  "Kazakhstan": ["Kazakhstan"],
  "Kenya": ["Kenya"],
  "Latvia": ["Latvia"],
  "Lesotho": ["Lesotho"],
  "Liberia": ["Liberia"],
  "Libya": ["Libya"],
  "Lithuania": ["Lithuania"],
  "Luxembourg": ["Luxembourg"],
  "MERCOSUR": ["Argentina", "Brazil", "Chile", "Colombia", "Ecuador", "Guyana", "Paraguay", "Peru", "Suriname", "Uruguay"],
  "Madagascar": ["Madagascar"],
  "Malawi": ["Malawi"],
  "Mali": ["Mali"],
  "Malta": ["Malta"],
  "Mauritania": ["Mauritania"],
  "Mauritius": ["Mauritius"],
  "Mexico": ["Mexico"],
  "Middle African countries": ["Angola", "Cameroon", "Central African Rep.", "Chad", "Congo", "Dem. Rep. of the Congo", "Equatorial Guinea", "Gabon", "Sao Tome and Principe"],
  "Morocco": ["Morocco"],
  "Mozambique": ["Mozambique"],
  "Namibia": ["Namibia"],
  "Netherlands": ["Netherlands"],
  "Niger": ["Niger"],
  "Nigeria": ["Nigeria"],
  "Northern African countries": ["Algeria", "Egypt", "Libya", "Morocco", "Sudan", "Tunisia"],
  "Norway": ["Norway"],
  "Paraguay": ["Paraguay"],
  "Peru": ["Peru"],
  "Poland": ["Poland"],
  "Portugal": ["Portugal"],
  "Qatar": ["Qatar"],
  "Rep. of Korea": ["Rep. of Korea"],
  "Romania": ["Romania"],
  "Russian Federation": ["Russian Federation"],
  "Rwanda": ["Rwanda"],
  "Sahel countries": ["Burkina Faso", "Cameroon", "Chad", "Gambia", "Guinea", "Mali", "Mauritania", "Niger", "Nigeria", "Senegal"],
  "Sao Tome and Principe": ["Sao Tome and Principe"],
  "Saudi Arabia": ["Saudi Arabia"],
  "Senegal": ["Senegal"],
  "Seychelles": ["Seychelles"],
  "Sierra Leone": ["Sierra Leone"],
  "Slovakia": ["Slovakia"],
  "Slovenia": ["Slovenia"],
  "Somalia": ["Somalia"],
  "South Africa": ["South Africa"],
  "South Sudan": ["South Sudan"],
  "Southern African countries": ["Botswana", "Eswatini", "Lesotho", "Namibia", "South Africa"],
  "Spain": ["Spain"],
  "Sub-saharan countries": ["Angola", "Benin", "Botswana", "Burkina Faso", "Burundi", "Cabo Verde", "Cameroon", "Central African Rep.", "Chad", "Comoros", "Congo", "Côte d'Ivoire", "Dem. Rep. of the Congo", "Djibouti", "Equatorial Guinea", "Eritrea", "Eswatini", "Ethiopia", "Gabon", "Gambia", "Ghana", "Guinea", "Guinea-Bissau", "Kenya", "Lesotho", "Liberia", "Madagascar", "Malawi", "Mali", "Mauritania", "Mauritius", "Mozambique", "Namibia", "Niger", "Nigeria", "Rwanda", "Sao Tome and Principe", "Senegal", "Seychelles", "Sierra Leone", "Somalia", "South Africa", "South Sudan", "Sudan", "Togo", "Uganda", "United Rep. of Tanzania", "Zambia", "Zimbabwe"],
  "Sudan": ["Sudan"],
  "Suriname": ["Suriname"],
  "Sweden": ["Sweden"],
  "Switzerland": ["Switzerland"],
  "Togo": ["Togo"],
  "Tunisia": ["Tunisia"],
  "Türkiye": ["Türkiye"],
  "USA": ["USA"],
  "Uganda": ["Uganda"],
  "United Arab Emirates": ["United Arab Emirates"],
  "United Kingdom": ["United Kingdom"],
  "United Rep. of Tanzania": ["United Rep. of Tanzania"],
  "Uruguay": ["Uruguay"],
  "Viet Nam": ["Viet Nam"],
  "Western African countries": ["Benin", "Burkina Faso", "Cabo Verde", "Côte d'Ivoire", "Gambia", "Ghana", "Guinea", "Guinea-Bissau", "Liberia", "Mali", "Mauritania", "Niger", "Nigeria", "Senegal", "Sierra Leone", "Togo"],
  "Zambia": ["Zambia"],
  "Zimbabwe": ["Zimbabwe"],
};
