export const timeRange = [
  2002,
  2023
];

export const categories = [
  "Arms and ammunition",
  "Art, collectibles",
  "Base metals",
  "Chemical products",
  "Edible fats",
  "Food, beverages, spirits, tobacco",
  "Footwear, headgear, other wearables",
  "Live animals, animal products",
  "Machinery",
  "Mineral products",
  "Miscellaneous manufactured articles",
  "Optical, precision instruments",
  "Paper products",
  "Pearls, precious metals and stones",
  "Plastic, rubber products",
  "Skin, leather products",
  "Stone, ceramic, glass products",
  "Textiles",
  "Vegetable products",
  "Vehicles, aircraft, other transport",
  "Wood products"
];

export const groupMappings = {
  "G7 countries": ["Canada", "France", "Germany", "Italy", "Japan", "USA", "United Kingdom"],
  "EU27 countries": ["Austria", "Belgium", "Bulgaria", "Croatia", "Cyprus", "Czechia", "Denmark", "Estonia", "Finland", "France", "Germany", "Greece", "Hungary", "Ireland", "Italy", "Latvia", "Lithuania", "Luxembourg", "Malta", "Netherlands", "Poland", "Portugal", "Romania", "Slovakia", "Slovenia", "Spain", "Sweden"],
  "Africa, total": ["Algeria", "Angola", "Benin", "Botswana", "Burkina Faso", "Burundi", "Cabo Verde", "Cameroon", "Central African Rep.", "Chad", "Comoros", "Congo", "Côte d'Ivoire", "Dem. Rep. of the Congo", "Djibouti", "Egypt", "Equatorial Guinea", "Eritrea", "Eswatini", "Ethiopia", "Gabon", "Gambia", "Ghana", "Guinea", "Guinea-Bissau", "Kenya", "Lesotho", "Liberia", "Libya", "Madagascar", "Malawi", "Mali", "Mauritania", "Mauritius", "Morocco", "Mozambique", "Namibia", "Niger", "Nigeria", "Rwanda", "Sao Tome and Principe", "Senegal", "Seychelles", "Sierra Leone", "Somalia", "South Africa", "South Sudan", "Sudan", "Togo", "Tunisia", "Uganda", "United Rep. of Tanzania", "Zambia", "Zimbabwe"],
  "Northern African countries": ["Algeria", "Egypt", "Libya", "Morocco", "Sudan", "Tunisia"],
  "Middle African countries": ["Angola", "Cameroon", "Central African Rep.", "Chad", "Congo", "Dem. Rep. of the Congo", "Equatorial Guinea", "Gabon", "Sao Tome and Principe"],
  "Western African countries": ["Benin", "Burkina Faso", "Côte d'Ivoire", "Gambia", "Ghana", "Guinea", "Guinea-Bissau", "Liberia", "Mali", "Mauritania", "Niger", "Nigeria", "Senegal", "Sierra Leone", "Togo"],
  "Eastern African countries": ["Burundi", "Comoros", "Djibouti", "Eritrea", "Ethiopia", "Kenya", "Madagascar", "Malawi", "Mauritius", "Mozambique", "Rwanda", "Seychelles", "Somalia", "South Sudan", "Sudan", "Uganda", "United Rep. of Tanzania", "Zambia", "Zimbabwe"],
  "Southern African countries": ["Botswana", "Eswatini", "Lesotho", "Namibia", "South Africa"],
  "Horn of Africa countries": ["Djibouti", "Eritrea", "Ethiopia", "Somalia"],
  "Sahel countries": ["Burkina Faso", "Cameroon", "Chad", "Gambia", "Guinea", "Mali", "Mauritania", "Niger", "Nigeria", "Senegal"],
  "Sub-saharan countries": ["Angola", "Benin", "Botswana", "Burkina Faso", "Burundi", "Cabo Verde", "Cameroon", "Central African Rep.", "Chad", "Comoros", "Congo", "Côte d'Ivoire", "Dem. Rep. of the Congo", "Djibouti", "Equatorial Guinea", "Eritrea", "Eswatini", "Ethiopia", "Gabon", "Gambia", "Ghana", "Guinea", "Guinea-Bissau", "Kenya", "Lesotho", "Liberia", "Madagascar", "Malawi", "Mali", "Mauritania", "Mauritius", "Mozambique", "Namibia", "Niger", "Nigeria", "Rwanda", "Sao Tome and Principe", "Senegal", "Seychelles", "Sierra Leone", "Somalia", "South Africa", "South Sudan", "Sudan", "Togo", "Uganda", "United Rep. of Tanzania", "Zambia", "Zimbabwe"],
  "Austria": ["Austria"],
  "Belgium": ["Belgium"],
  "Brazil": ["Brazil"],
  "Canada": ["Canada"],
  "China": ["China"],
  "Croatia": ["Croatia"],
  "Cyprus": ["Cyprus"],
  "Czechia": ["Czechia"],
  "Denmark": ["Denmark"],
  "Estonia": ["Estonia"],
  "Finland": ["Finland"],
  "Greece": ["Greece"],
  "Hungary": ["Hungary"],
  "India": ["India"],
  "Ireland": ["Ireland"],
  "Japan": ["Japan"],
  "Latvia": ["Latvia"],
  "Lithuania": ["Lithuania"],
  "Luxembourg": ["Luxembourg"],
  "Malta": ["Malta"],
  "Netherlands": ["Netherlands"],
  "Poland": ["Poland"],
  "Portugal": ["Portugal"],
  "Romania": ["Romania"],
  "Slovakia": ["Slovakia"],
  "Slovenia": ["Slovenia"],
  "Spain": ["Spain"],
  "Sweden": ["Sweden"],
  "USA": ["USA"],
  "United Kingdom": ["United Kingdom"],
  "Algeria": ["Algeria"],
  "Angola": ["Angola"],
  "Benin": ["Benin"],
  "Botswana": ["Botswana"],
  "Burkina Faso": ["Burkina Faso"],
  "Burundi": ["Burundi"],
  "Cabo Verde": ["Cabo Verde"],
  "Cameroon": ["Cameroon"],
  "Central African Rep.": ["Central African Rep."],
  "Chad": ["Chad"],
  "Comoros": ["Comoros"],
  "Congo": ["Congo"],
  "Côte d'Ivoire": ["Côte d'Ivoire"],
  "Dem. Rep. of the Congo": ["Dem. Rep. of the Congo"],
  "Djibouti": ["Djibouti"],
  "Egypt": ["Egypt"],
  "Equatorial Guinea": ["Equatorial Guinea"],
  "Eritrea": ["Eritrea"],
  "Eswatini": ["Eswatini"],
  "Ethiopia": ["Ethiopia"],
  "Gabon": ["Gabon"],
  "Gambia": ["Gambia"],
  "Ghana": ["Ghana"],
  "Guinea": ["Guinea"],
  "Guinea-Bissau": ["Guinea-Bissau"],
  "Kenya": ["Kenya"],
  "Lesotho": ["Lesotho"],
  "Liberia": ["Liberia"],
  "Libya": ["Libya"],
  "Madagascar": ["Madagascar"],
  "Malawi": ["Malawi"],
  "Mali": ["Mali"],
  "Mauritania": ["Mauritania"],
  "Mauritius": ["Mauritius"],
  "Morocco": ["Morocco"],
  "Mozambique": ["Mozambique"],
  "Namibia": ["Namibia"],
  "Niger": ["Niger"],
  "Nigeria": ["Nigeria"],
  "Rwanda": ["Rwanda"],
  "Sao Tome and Principe": ["Sao Tome and Principe"],
  "Senegal": ["Senegal"],
  "Seychelles": ["Seychelles"],
  "Sierra Leone": ["Sierra Leone"],
  "Somalia": ["Somalia"],
  "South Africa": ["South Africa"],
  "South Sudan": ["South Sudan"],
  "Sudan": ["Sudan"],
  "Togo": ["Togo"],
  "Tunisia": ["Tunisia"],
  "Uganda": ["Uganda"],
  "United Rep. of Tanzania": ["United Rep. of Tanzania"],
  "Zambia": ["Zambia"],
  "Zimbabwe": ["Zimbabwe"]
}