export const timeRange = [
  2002,
  2023
];

export const categories = [
  "Arms and ammunition",
  "Art, collectibles",
  "Base metals",
  "Chemical products",
  "Edible fats",
  "Food, beverages, spirits, tobacco",
  "Footwear, headgear, other wearables",
  "Live animals, animal products",
  "Machinery",
  "Mineral products",
  "Miscellaneous manufactured articles",
  "Optical, precision instruments",
  "Paper products",
  "Pearls, precious metals and stones",
  "Plastic, rubber products",
  "Skin, leather products",
  "Stone, ceramic, glass products",
  "Textiles",
  "Vegetable products",
  "Vehicles, aircraft, other transport",
  "Wood products"
];

export const groupMappings = {
  "African countries": ["Algeria", "Angola", "Benin", "Botswana", "Burkina Faso", "Burundi", "Cabo Verde", "Cameroon", "Central African Rep.", "Chad", "Comoros", "Congo", "Côte d'Ivoire", "Dem. Rep. of the Congo", "Djibouti", "Egypt", "Equatorial Guinea", "Eritrea", "Eswatini", "Ethiopia", "Gabon", "Gambia", "Ghana", "Guinea", "Guinea-Bissau", "Kenya", "Lesotho", "Liberia", "Libya", "Madagascar", "Malawi", "Mali", "Mauritania", "Mauritius", "Morocco", "Mozambique", "Namibia", "Niger", "Nigeria", "Rwanda", "Sao Tome and Principe", "Senegal", "Seychelles", "Sierra Leone", "Somalia", "South Africa", "South Sudan", "Sudan", "Togo", "Tunisia", "Uganda", "United Rep. of Tanzania", "Zambia", "Zimbabwe"],
  "Algeria": ["Algeria"],
  "Angola": ["Angola"],
  "Argentina": ["Argentina"],
  "Australia": ["Australia"],
  "Austria": ["Austria"],
  "BRICS countries": ["Brazil", "China", "Egypt", "Ethiopia", "India", "Indonesia", "Iran", "Russian Federation", "United Arab Emirates"],
  "Belgium": ["Belgium"],
  "Benin": ["Benin"],
  "Botswana": ["Botswana"],
  "Brazil": ["Brazil"],
  "Bulgaria": ["Bulgaria"],
  "Burkina Faso": ["Burkina Faso"],
  "Burundi": ["Burundi"],
  "Cabo Verde": ["Cabo Verde"],
  "Cameroon": ["Cameroon"],
  "Canada": ["Canada"],
  "Central African Rep.": ["Central African Rep."],
  "Chad": ["Chad"],
  "China": ["China"],
  "Comoros": ["Comoros"],
  "Congo": ["Congo"],
  "Croatia": ["Croatia"],
  "Cyprus": ["Cyprus"],
  "Czechia": ["Czechia"],
  "Côte d'Ivoire": ["Côte d'Ivoire"],
  "Dem. Rep. of the Congo": ["Dem. Rep. of the Congo"],
  "Denmark": ["Denmark"],
  "Djibouti": ["Djibouti"],
  "EU27 countries": ["Austria", "Belgium", "Bulgaria", "Croatia", "Cyprus", "Czechia", "Denmark", "Estonia", "Finland", "France", "Germany", "Greece", "Hungary", "Ireland", "Italy", "Latvia", "Lithuania", "Luxembourg", "Malta", "Netherlands", "Poland", "Portugal", "Romania", "Slovakia", "Slovenia", "Spain", "Sweden"],
  "Eastern African countries": ["Burundi", "Comoros", "Djibouti", "Eritrea", "Ethiopia", "Kenya", "Madagascar", "Malawi", "Mauritius", "Mozambique", "Rwanda", "Seychelles", "Somalia", "South Sudan", "Uganda", "United Rep. of Tanzania", "Zambia", "Zimbabwe"],
  "Egypt": ["Egypt"],
  "Equatorial Guinea": ["Equatorial Guinea"],
  "Eritrea": ["Eritrea"],
  "Estonia": ["Estonia"],
  "Eswatini": ["Eswatini"],
  "Ethiopia": ["Ethiopia"],
  "Finland": ["Finland"],
  "France": ["France"],
  "G20 countries": ["Argentina", "Australia", "Brazil", "Canada", "China", "France", "Germany", "India", "Indonesia", "Italy", "Japan", "Mexico", "Rep. of Korea", "Russian Federation", "Saudi Arabia", "South Africa", "Türkiye", "USA", "United Kingdom"],
  "G7 countries": ["Canada", "France", "Germany", "Italy", "Japan", "USA", "United Kingdom"],
  "Gabon": ["Gabon"],
  "Gambia": ["Gambia"],
  "Germany": ["Germany"],
  "Ghana": ["Ghana"],
  "Greece": ["Greece"],
  "Guinea": ["Guinea"],
  "Guinea-Bissau": ["Guinea-Bissau"],
  "Horn of Africa countries": ["Djibouti", "Eritrea", "Ethiopia", "Somalia"],
  "Hungary": ["Hungary"],
  "India": ["India"],
  "Indonesia": ["Indonesia"],
  "Iran": ["Iran"],
  "Ireland": ["Ireland"],
  "Italy": ["Italy"],
  "Japan": ["Japan"],
  "Kenya": ["Kenya"],
  "Latvia": ["Latvia"],
  "Lesotho": ["Lesotho"],
  "Liberia": ["Liberia"],
  "Libya": ["Libya"],
  "Lithuania": ["Lithuania"],
  "Luxembourg": ["Luxembourg"],
  "Madagascar": ["Madagascar"],
  "Malawi": ["Malawi"],
  "Mali": ["Mali"],
  "Malta": ["Malta"],
  "Mauritania": ["Mauritania"],
  "Mauritius": ["Mauritius"],
  "Mexico": ["Mexico"],
  "Middle African countries": ["Angola", "Cameroon", "Central African Rep.", "Chad", "Congo", "Dem. Rep. of the Congo", "Equatorial Guinea", "Gabon", "Sao Tome and Principe"],
  "Morocco": ["Morocco"],
  "Mozambique": ["Mozambique"],
  "Namibia": ["Namibia"],
  "Netherlands": ["Netherlands"],
  "Niger": ["Niger"],
  "Nigeria": ["Nigeria"],
  "Northern African countries": ["Algeria", "Egypt", "Libya", "Morocco", "Sudan", "Tunisia"],
  "Poland": ["Poland"],
  "Portugal": ["Portugal"],
  "Rep. of Korea": ["Rep. of Korea"],
  "Romania": ["Romania"],
  "Russian Federation": ["Russian Federation"],
  "Rwanda": ["Rwanda"],
  "Sahel countries": ["Burkina Faso", "Cameroon", "Chad", "Gambia", "Guinea", "Mali", "Mauritania", "Niger", "Nigeria", "Senegal"],
  "Sao Tome and Principe": ["Sao Tome and Principe"],
  "Saudi Arabia": ["Saudi Arabia"],
  "Senegal": ["Senegal"],
  "Seychelles": ["Seychelles"],
  "Sierra Leone": ["Sierra Leone"],
  "Slovakia": ["Slovakia"],
  "Slovenia": ["Slovenia"],
  "Somalia": ["Somalia"],
  "South Africa": ["South Africa"],
  "South Sudan": ["South Sudan"],
  "Southern African countries": ["Botswana", "Eswatini", "Lesotho", "Namibia", "South Africa"],
  "Spain": ["Spain"],
  "Sub-saharan countries": ["Angola", "Benin", "Botswana", "Burkina Faso", "Burundi", "Cabo Verde", "Cameroon", "Central African Rep.", "Chad", "Comoros", "Congo", "Côte d'Ivoire", "Dem. Rep. of the Congo", "Djibouti", "Equatorial Guinea", "Eritrea", "Eswatini", "Ethiopia", "Gabon", "Gambia", "Ghana", "Guinea", "Guinea-Bissau", "Kenya", "Lesotho", "Liberia", "Madagascar", "Malawi", "Mali", "Mauritania", "Mauritius", "Mozambique", "Namibia", "Niger", "Nigeria", "Rwanda", "Sao Tome and Principe", "Senegal", "Seychelles", "Sierra Leone", "Somalia", "South Africa", "South Sudan", "Sudan", "Togo", "Uganda", "United Rep. of Tanzania", "Zambia", "Zimbabwe"],
  "Sudan": ["Sudan"],
  "Sweden": ["Sweden"],
  "Togo": ["Togo"],
  "Tunisia": ["Tunisia"],
  "Türkiye": ["Türkiye"],
  "USA": ["USA"],
  "Uganda": ["Uganda"],
  "United Arab Emirates": ["United Arab Emirates"],
  "United Kingdom": ["United Kingdom"],
  "United Rep. of Tanzania": ["United Rep. of Tanzania"],
  "Western African countries": ["Benin", "Burkina Faso", "Cabo Verde", "Côte d'Ivoire", "Gambia", "Ghana", "Guinea", "Guinea-Bissau", "Liberia", "Mali", "Mauritania", "Niger", "Nigeria", "Senegal", "Sierra Leone", "Togo"],
  "Zambia": ["Zambia"],
  "Zimbabwe": ["Zimbabwe"],
};
